### ISSUE TITLE
Update CI to use Solutions & Portable DebugTypes

### ISSUE THREAD

**Issue by carusology** [invio/Invio.Hashing#18]
**Background**
As part of our migration to v1.0.4 of the .NET SDK, I [set the `DebugType` to `full`](https://github.com/invio/Invio.Hashing/blob/02b4a2878ee426067c20466e51be9b5d46e15a13/src/Invio.Hashing/Invio.Hashing.csproj#L8) and updated the CI scripts to explicitly reference XML-based `*.csproj` files due to the removal of `global.json` and `project.json`. The `DebugType` really should be `portable` for .NET Core when we pack the code (though it needs to be `full` for when we run opencover on it), and we should add a `*.sln` to manage our `*.csproj` files.

**Task**
* [x] Update the repository to have a `Invio.Hashing.sln` solution at the root of the repository that references the source and test projects.
* [x] Update `Invio.Hashing.Tests.csproj` such that `<IsPackable>false</IsPackable>` is specified.
* [x] Restore `set-debug-type.ps1`, but with it updating the `DebugType` via the XML-based `Invio.Hashing.csproj` instead of JSON-based `project.json`.
